#!/bin/bash

function usage() {
  echo 'usage: git rstash list [<user>] [<remote>]'
  echo '   or: git rstash pull [<user>] [<remote>]'
  echo '   or: git rstash push [<remote>]'
  echo '   or: git rstash purge [<user>] [<remote>]'
  echo ''
  echo 'advanced usages:'
  echo 'git rstash list-all [<remote>]'
  echo 'git rstash list-sha [<user>] [<remote>]'
  echo 'git rstash list-sha-all [<remote>]'
  echo 'git rstash pull-all [<remote>]'
  echo 'git rstash pull-only [<user>] [<remote>]'
  echo 'git rstash pull-only-all [<remote>]'
  echo 'git rstash push-one <stash> [<remote>]'
  echo 'git rstash purge-all [<remote>]'
  echo 'git rstash drop <stash> [<remote>] ['\''y'\''|'\''n'\'']'
  echo 'git rstash import <SHA>'
  echo 'git rstash import-all'
  echo ''
}

function list() {
  username=$(git config user.name)
  [ -z "$1" ] || username="$1"
  remote=origin
  [ -z "$2" ] || remote="$2"

  git ls-remote "$remote" refs/stashes/$username/* | awk '{print $2}' | awk '!/^$/'
}

function list-sha() {
  username=$(git config user.name)
  [ -z "$1" ] || username="$1"
  remote=origin
  [ -z "$2" ] || remote="$2"

  git ls-remote "$remote" refs/stashes/$username/* | awk '{print $1}' | awk '!/^$/'
}

function list-all() {
  remote=origin
  [ -z "$1" ] || remote="$1"

  git ls-remote "$remote" refs/stashes/* | awk '{print $2}' | awk '!/^$/'
}

function list-sha-all() {
  remote=origin
  [ -z "$1" ] || remote="$1"

  git ls-remote "$remote" refs/stashes/* | awk '{print $1}' | awk '!/^$/'
}

function push-one() {
  username=$(git config user.name)

  [ -z "$1" ] && echo 'Error: please specify a stash number to push.' && exit 2
  remote=origin
  [ -z "$2" ] || remote="$2"

  echo "Pushing stash $1 to $remote."

  git push $remote stash@{$1}:refs/stashes/$username/$(git rev-parse --short stash@{$1})
}

function pull-only() {
  username=$(git config user.name)
  [ -z "$1" ] || username="$1"
  remote=origin
  [ -z "$2" ] || remote="$2"

  git fetch "$remote" refs/stashes/$username/*:refs/stashes/$username/*
}

function pull-only-all() {
  remote=origin
  [ -z "$1" ] || remote="$1"

  git fetch "$remote" refs/stashes/*:refs/stashes/*
}

function pull() {
  username=$(git config user.name)
  [ -z "$1" ] || username="$1"
  remote=origin
  [ -z "$2" ] || remote="$2"

  pull-only $username $remote
  import-all
}

function pull-all() {
  remote=origin
  [ -z "$1" ] || remote="$1"
  
  pull-only-all $remote
  import-all
}

function drop() {
  remote=origin
  [ -z "$1" ] && echo 'Error: please specify a stash number to drop.' && exit 3
  stashNum="$1"
  shift
  [ -z "$1" ] || remote="$1"
  stashCommit=$(git rev-parse --short stash@{$stashNum})
  shift
  if [ -z "$1" ]
  then
    read -p "Really delete stash $stashNum (commit $stashCommit) from $remote? " answer
  else
    answer="$1"
  fi
  if [ "$answer" == 'y' ]
  then
    git push $remote :refs/stashes/$username/$stashCommit
  fi
}

function import() {
  SHA=''
  if [ -z "$1" ]
  then
    echo 'Error: please specify a SHA to import as a stash.'
    exit 4
  else
    SHA="$1"
  fi

  all=($(git stash list | awk '{print $1}' | awk '!/^$/' | sed 's/.$//'))

  # Start at 1 because Git won't save if duplicate of stash 0.
  for i in ${all}
  do
    # If commit matches existing stash, abort early.
    diff <(git rev-parse $i) <(git rev-parse $SHA) >/dev/null && return 0
  done

  git stash store --message "$(git show --no-patch --format=format:%s $SHA)" $SHA
}

function push() {
  remote=origin
  [ -z "$1" ] || remote="$1"

  for i in $(seq 0 $(expr $(git rev-list --walk-reflogs --count stash) - 1))
  do
    push-one $i "$remote"
  done
}

function purge() {
  username=$(git config user.name)
  [ -z "$1" ] || username="$1"
  remote=origin
  [ -z "$2" ] || remote="$2"
  all=($(list $username $remote))
  if [ ${#all[@]} == 0 ]
  then
    echo 'Error: no stashes found in remote.'
    return 0
  fi

  for stash in $all
  do
    git push "$remote" :"$stash"
  done
}

function purge-all() {
  remote=origin
  [ -z "$1" ] || remote="$1"
  all=($(list-all $remote))
  if [ ${#all[@]} == 0 ]
  then
    echo 'Error: no stashes found in remote.'
    return 0
  fi

  for stash in $all
  do
    git push "$remote" :"$stash"
  done
}

function import-all() {
  if [ ! -d .git/refs/stashes ]
  then
    echo 'Error: no stashes pulled or not in a Git repo.'
    return 0
  fi

  all=($(find .git/refs/stashes -type f -exec basename {} \;))

  for stash in $all
  do
    import "$stash"
  done
}

case "$1" in
  list|list-all|list-sha|list-sha-all|push|push-one|pull|pull-all|pull-only|pull-only-all|import|import-all|purge|purge-all)
    "$@"
    ;;
  drop|remove|delete)
    shift
    drop "$@"
    ;;
  -h)
    usage
    exit 0
    ;;
  *)
    usage
    exit 1
    ;;
esac
